### ISSUE TITLE
Refactor 3Di Toolbox as results-analysis-only toolbox

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#598]
Everything that has to do with result analysis should be independent from the spatialite.

Strip all functionalities from 3Di Toolbox except results analysis. This will make it possible to introduce the 3Di Schematisation Editor / Geopackage as replacement of the current method for loading models (from spatialite). Also makes code easier to maintain and limits the impact of failing python dependencies.

Convert 'commands' to Processing Algorithms:
- [x] Raster checker to separate python package (#597) to make it available in 3Di API Client plugin
- [ ] Remove schematization checker and make it available in 3Di API Client plugin
- [ ] Convert 'Import SufHyd' to processing algorithm, make suitable for GeoPackage
- [ ] Convert 'Guess indicators' to processing algorithm(s), make data provider agnostic or at least suitable for GeoPackage
- [ ] Control structures, make suitable for GeoPackage. Incorporate in 3Di Model Editor (or phase out)
- [ ] Create breach locations to processing algorithm, make data provider agnostic or at least suitable for GeoPackage
- [ ] Add connected points to processing algorithm, make data provider agnostic or at least suitable for GeoPackage
- [ ] Predict calculation points to processing algorithm, make data provider agnostic or at least suitable for GeoPackage

Connect to new #662
- [x] #665
- [x] #666
- [x] #667
- [x] #668
- [x] #669
- [x] #670

General
- [ ] Move processing algorithms to separate plugin (3Di Processing)
- [ ] Delete all references to the spatialite from remaining functionality

**Comment by leendertvanwolfswinkel** [comment]
@Jonasvsl @Patrick-Nijman
